// Campus Store Product Catalog
// Features exact user-provided product images and accurate pricing
const PRODUCTS_DATA = [
  // ==========================================
  // 1. STATIONARY ESSENTIALS
  // ==========================================
  {
    id: "stat-001",
    name: "Practical Notebook (200 Pages) - Science",
    category: "stationary",
    categoryLabel: "Stationary Essentials",
    price: 110,
    cost: 65,
    originalPrice: 120,
    rating: 4.9,
    reviewsCount: 184,
    badge: "Official 200 Pages",
    description: "Universal Science Practical Notebook (200 Pages) for laboratory course work. High-quality paper with one side ruled and one side plain/blank for diagrams, complete with pre-printed index and Carl Sagan quote cover.",
    specs: ["200 Pages (100 Sheets)", "One side ruled, one side blank", "Hardbound laminated cover with Carl Sagan quote", "Pre-printed Index & Teacher signature columns", "Standard Lab Manual size"],
    inStock: true,
    stockCount: 110,
    image: "assets/images/practical_notebook_200.jpg",
    gallery: [
      "assets/images/practical_notebook_200.jpg",
      "assets/images/practical_notebook_back.jpg"
    ],
    tags: ["notebook", "practical", "lab", "stationary", "universal", "science", "200 pages"]
  },
  {
    id: "stat-002",
    name: "Practical Notebook (144 Pages) - Science",
    category: "stationary",
    categoryLabel: "Stationary Essentials",
    price: 70,
    cost: 40,
    originalPrice: 80,
    rating: 4.8,
    reviewsCount: 142,
    badge: "144 Pages",
    description: "Universal Science Practical Notebook (144 Pages) for semester laboratory experiments, chemistry, physics, biology, and workshop assignments. Features clean white science cover with apparatus artwork and pre-printed checklist.",
    specs: ["144 Pages (72 Sheets)", "Premium 70 GSM smooth lab paper", "Pre-printed barcode & page checklist", "One side ruled, one side blank for drawings", "Durable binding with protective finish"],
    inStock: true,
    stockCount: 150,
    image: "assets/images/practical_notebook_144.jpg",
    gallery: [
      "assets/images/practical_notebook_144.jpg",
      "assets/images/practical_notebook_back.jpg"
    ],
    tags: ["notebook", "practical", "assignment", "stationary", "universal", "144 pages"]
  },
  {
    id: "stat-003",
    name: "A4 Assignment Sheets Bundle (100 Sheets)",
    category: "stationary",
    categoryLabel: "Stationary Essentials",
    price: 90,
    cost: 55,
    originalPrice: 110,
    rating: 4.9,
    reviewsCount: 215,
    badge: "Popular",
    description: "Premium university grade one-side ruled assignment sheets with top margin and student details header (Student ID, Section, Subject).",
    specs: ["100 Single Sheets", "75 GSM Bright White Paper", "One Side Ruled, One Side Plain", "Standard Punch Holes"],
    inStock: true,
    stockCount: 200,
    image: "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?auto=format&fit=crop&w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1586075010923-2dd4570fb338?auto=format&fit=crop&w=600&q=80"],
    tags: ["assignment", "sheets", "a4", "stationary"]
  },
  {
    id: "stat-004",
    name: "Executive Ball & Gel Pen Set (Pack of 5)",
    category: "stationary",
    categoryLabel: "Stationary Essentials",
    price: 60,
    cost: 35,
    originalPrice: 75,
    rating: 4.8,
    reviewsCount: 180,
    badge: "Value Pack",
    description: "Smooth-flow waterproof ink pens (3 Blue, 1 Black, 1 Red) for rapid exam writing and clear note-taking.",
    specs: ["0.7mm fine tip", "Fast drying waterproof ink", "Soft rubberized grip", "Exam approved"],
    inStock: true,
    stockCount: 150,
    image: "https://images.unsplash.com/photo-1585336261026-7f41a99ef87b?auto=format&fit=crop&w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1585336261026-7f41a99ef87b?auto=format&fit=crop&w=600&q=80"],
    tags: ["pen", "gel pen", "exam", "stationary"]
  },
  {
    id: "stat-005",
    name: "Scientific Calculator Hard Shell Protective Case",
    category: "stationary",
    categoryLabel: "Stationary Essentials",
    price: 249,
    cost: 150,
    originalPrice: 349,
    rating: 4.9,
    reviewsCount: 77,
    badge: "Protective",
    description: "Shockproof EVA storage case designed specifically for scientific calculators and digital accessories.",
    specs: ["Shockproof EVA Shell", "Internal Mesh Pocket for cables/pens", "Soft inner velvet lining", "Heavy-duty zipper"],
    inStock: true,
    stockCount: 30,
    image: "https://images.unsplash.com/photo-1594980596870-8aa52a78d8cd?auto=format&fit=crop&w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1594980596870-8aa52a78d8cd?auto=format&fit=crop&w=600&q=80"],
    tags: ["calculator", "case", "protective", "casio"]
  },

  // ==========================================
  // 2. GYM ESSENTIALS
  // ==========================================
  {
    id: "gym-001",
    name: "Heavy Duty Gym Wrist Band (Pair with Thumb Loops)",
    category: "gym",
    categoryLabel: "Gym Essentials",
    price: 199,
    cost: 120,
    originalPrice: 299,
    rating: 4.9,
    reviewsCount: 135,
    badge: "Heavy Support",
    description: "High-grade elastic wrist wraps featuring red power stripes, heavy-duty Velcro locking system, and reinforced thumb loop. Provides maximum joint stability for bench presses, pull-ups, overhead presses, and heavy gym lifting.",
    specs: ["Pair of 2 Wrist Wraps (Left & Right)", "18-Inch high-tension elastic cotton", "Reinforced thumb loop for firm positioning", "Super durable industrial-strength Velcro fastening", "Ideal for Powerlifting, Crossfit & Pull-ups"],
    inStock: true,
    stockCount: 45,
    image: "assets/images/gym_wrist_band_main.jpg",
    gallery: [
      "assets/images/gym_wrist_band_main.jpg",
      "assets/images/gym_wrist_band_pullup.jpg"
    ],
    tags: ["wrist band", "wrist wrap", "gym", "workout", "fitness", "pullups", "benchpress"]
  },
  {
    id: "gym-002",
    name: "Cylindrical Gym Duffel Bag with Shoe Compartment",
    category: "gym",
    categoryLabel: "Gym Essentials",
    price: 699,
    cost: 420,
    originalPrice: 999,
    rating: 4.9,
    reviewsCount: 110,
    badge: "Bestseller",
    description: "Spacious multi-utility gym barrel duffel bag with honeycomb texture fabric, dedicated ventilated sneaker compartment, adjustable padded shoulder strap, and ample room for shaker, clothes, towels, and workout accessories.",
    specs: ["35-Liter capacity cylindrical barrel design", "Separate isolated shoe tunnel with air grommets", "Water-resistant honeycomb ripstop fabric", "Reinforced carry handles + padded shoulder strap", "Multiple organizer pockets for student ID & keys"],
    inStock: true,
    stockCount: 30,
    image: "assets/images/gym_duffel_bag_main.jpg",
    gallery: [
      "assets/images/gym_duffel_bag_main.jpg",
      "assets/images/gym_duffel_bag_flatlay.jpg"
    ],
    tags: ["gym bag", "duffel", "shoes", "fitness", "gym", "barrel bag"]
  },
  {
    id: "gym-003",
    name: "Leatherette Weightlifting Gym Gloves with Wrist Wrap",
    category: "gym",
    categoryLabel: "Gym Essentials",
    price: 349,
    cost: 210,
    originalPrice: 499,
    rating: 4.8,
    reviewsCount: 125,
    badge: "360° Thumb Movement",
    description: "Ergonomic half-finger workout gloves crafted with soft-padded leatherette palm protection, 360-degree thumb articulation, easy-to-remove finger tabs, and super durable velcro wrist wraps to prevent calluses and wrist strain.",
    specs: ["Cross-stitched soft padded leatherette palm", "Half-finger coverage with quick-pull removal tabs", "360-degree anatomical thumb movement", "Integrated elastic wrist strap with durable velcro", "Breathable mesh back for sweat ventilation"],
    inStock: true,
    stockCount: 60,
    image: "assets/images/gym_gloves_1.jpg",
    gallery: [
      "assets/images/gym_gloves_1.jpg",
      "assets/images/gym_gloves_2.jpg",
      "assets/images/gym_gloves_3.jpg"
    ],
    tags: ["gym gloves", "gloves", "weightlifting", "workout", "leatherette", "grip"]
  },
  {
    id: "gym-004",
    name: "3-Compartment Protein Shaker Bottle (500ml + Storage)",
    category: "gym",
    categoryLabel: "Gym Essentials",
    price: 299,
    cost: 180,
    originalPrice: 449,
    rating: 4.9,
    reviewsCount: 178,
    badge: "Made for the Bold",
    description: "Premium all-black 3-in-1 multi-compartment fitness shaker (500ml liquid capacity). Comes with detachable bottom protein powder storage jar, pill/capsule organizer tray, and built-in honeycomb mixer grid for lump-free protein shakes.",
    specs: ["500ml Main Liquid Chamber", "3 Detachable Compartments (Shaker + Powder Jar + Pill Tray)", "BPA-Free food-grade durable matte black finish", "Leakproof secure flip-cap with carry loop", "Includes blending grid for smooth lump-free mix"],
    inStock: true,
    stockCount: 75,
    image: "assets/images/gym_shaker_main.jpg",
    gallery: [
      "assets/images/gym_shaker_main.jpg",
      "assets/images/gym_shaker_parts.jpg",
      "assets/images/gym_shaker_powder.jpg"
    ],
    tags: ["shaker", "protein shaker", "gym shaker", "bottle", "3 compartments", "500ml"]
  },
  {
    id: "gym-005",
    name: "Resistance Loop Bands Set (5 Resistance Levels)",
    category: "gym",
    categoryLabel: "Gym Essentials",
    price: 399,
    cost: 240,
    originalPrice: 599,
    rating: 4.8,
    reviewsCount: 73,
    badge: "Hostel Workout",
    description: "Set of 5 natural latex resistance loop bands ranging from X-Light to X-Heavy for stretching, mobility, and hostel room workouts.",
    specs: ["5 Color-coded resistance bands", "100% Natural eco-latex", "Includes carry pouch & workout guide", "5 lbs to 40 lbs resistance range"],
    inStock: true,
    stockCount: 35,
    image: "https://images.unsplash.com/photo-1598289431512-b97b0917affc?auto=format&fit=crop&w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1598289431512-b97b0917affc?auto=format&fit=crop&w=600&q=80"],
    tags: ["resistance bands", "latex", "workout", "fitness"]
  },
  {
    id: "gym-006",
    name: "Quick-Dry Microfiber Gym Sweat Towel",
    category: "gym",
    categoryLabel: "Gym Essentials",
    price: 179,
    cost: 105,
    originalPrice: 249,
    rating: 4.6,
    reviewsCount: 52,
    badge: "Antimicrobial",
    description: "Ultra-absorbent, fast-drying compact microfiber sweat towel with corner zipper pocket for locker keys and ID.",
    specs: ["Size: 40cm x 80cm", "Dries 3x faster than cotton", "Hidden zip pocket", "Antibacterial treated"],
    inStock: true,
    stockCount: 45,
    image: "https://images.unsplash.com/photo-1616874535244-73aea5daadb9?auto=format&fit=crop&w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1616874535244-73aea5daadb9?auto=format&fit=crop&w=600&q=80"],
    tags: ["towel", "sweat towel", "microfiber", "gym"]
  },

  // ==========================================
  // 3. LAPTOP ACCESSORIES
  // ==========================================
  {
    id: "lap-001",
    name: "Wired Keyboard and Mouse Combo",
    category: "laptop",
    categoryLabel: "Laptop Accessories",
    price: 599,
    cost: 360,
    originalPrice: 799,
    rating: 4.7,
    reviewsCount: 130,
    badge: "Value Pick",
    description: "Reliable USB plug-and-play full-size keyboard with whisper-quiet keys and high-precision 1200 DPI optical mouse.",
    specs: ["USB Plug & Play (No driver needed)", "Spill-resistant key layout", "1200 DPI Optical Sensor", "1.5m Durable Cable"],
    inStock: true,
    stockCount: 30,
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=80"],
    tags: ["keyboard", "mouse", "wired", "laptop", "pc"]
  },
  {
    id: "lap-002",
    name: "Wireless Keyboard and Mouse Combo (2.4GHz)",
    category: "laptop",
    categoryLabel: "Laptop Accessories",
    price: 999,
    cost: 600,
    originalPrice: 1399,
    rating: 4.8,
    reviewsCount: 110,
    badge: "Bestseller",
    description: "Ultra-slim wireless desktop combo with single 2.4GHz nano receiver, silent chiclet keys, and auto-sleep battery saving technology.",
    specs: ["Single 2.4GHz Nano USB Receiver", "10-meter wireless range", "1600 DPI 3-level adjustable mouse", "Long battery life (up to 12 months)"],
    inStock: true,
    stockCount: 22,
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=600&q=80"],
    tags: ["wireless keyboard", "mouse", "wireless", "laptop"]
  },
  {
    id: "lap-003",
    name: "Laptop Cooling Fan Pad with Adjustable Stand",
    category: "laptop",
    categoryLabel: "Laptop Accessories",
    price: 799,
    cost: 480,
    originalPrice: 1199,
    rating: 4.8,
    reviewsCount: 84,
    badge: "Cooling Tech",
    description: "Heavy-duty multi-fan cooling pad with dual ultra-quiet 140mm fans, blue LED backlighting, dual USB pass-through ports, and 5 height angles.",
    specs: ["Fits laptops 12\" to 17.3\"", "Twin 1400 RPM Silent Fans", "5-Level Ergonomic Height Adjustment", "Dual USB 2.0 Passthrough Ports"],
    inStock: true,
    stockCount: 18,
    image: "https://images.unsplash.com/photo-1588702547923-7093a6c3ba33?auto=format&fit=crop&w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1588702547923-7093a6c3ba33?auto=format&fit=crop&w=600&q=80"],
    tags: ["cooling fan", "cooling pad", "laptop", "cooler", "stand"]
  },
  {
    id: "lap-004",
    name: "High-Speed Pendrive 32GB (USB 3.0)",
    category: "laptop",
    categoryLabel: "Laptop Accessories",
    price: 349,
    cost: 210,
    originalPrice: 499,
    rating: 4.9,
    reviewsCount: 175,
    badge: "Fast Transfer",
    description: "Compact metallic 32GB USB 3.0 flash drive with read speeds up to 130MB/s for swift lab code transfers and project submissions.",
    specs: ["32 GB Storage", "USB 3.0 (Up to 130 MB/s transfer)", "Robust all-metal casing with keyring loop", "5-Year Manufacturer Warranty"],
    inStock: true,
    stockCount: 50,
    image: "https://images.unsplash.com/photo-1618761714954-0b8cd0026356?auto=format&fit=crop&w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1618761714954-0b8cd0026356?auto=format&fit=crop&w=600&q=80"],
    tags: ["pendrive", "32gb", "usb", "flash drive", "storage"]
  },
  {
    id: "lap-005",
    name: "High-Speed Pendrive 64GB (USB 3.1)",
    category: "laptop",
    categoryLabel: "Laptop Accessories",
    price: 499,
    cost: 300,
    originalPrice: 699,
    rating: 4.9,
    reviewsCount: 190,
    badge: "Top Choice",
    description: "High-capacity 64GB USB 3.1 flash drive with password protection software and rapid read/write speeds for semester projects and media.",
    specs: ["64 GB Storage", "USB 3.1 Gen 1 (Up to 150 MB/s)", "SanDisk SecureAccess 128-bit AES encryption", "Sleek retractable design"],
    inStock: true,
    stockCount: 40,
    image: "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=600&q=80"],
    tags: ["pendrive", "64gb", "usb 3.1", "storage", "laptop"]
  },
  {
    id: "lap-006",
    name: "6-in-1 Aluminum USB-C Hub Adapter",
    category: "laptop",
    categoryLabel: "Laptop Accessories",
    price: 1299,
    cost: 780,
    originalPrice: 1799,
    rating: 4.9,
    reviewsCount: 65,
    badge: "Pro Grade",
    description: "Premium aluminum Type-C multiport adapter with 4K HDMI, 3x USB 3.0 ports, 100W PD charging port, and SD/TF card slots.",
    specs: ["4K@30Hz HDMI Output", "100W Power Delivery Pass-Through", "3x High-speed USB 3.0 Ports", "Heat dissipation aluminum body"],
    inStock: true,
    stockCount: 15,
    image: "https://images.unsplash.com/photo-1544652478-6653e09f18a2?auto=format&fit=crop&w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1544652478-6653e09f18a2?auto=format&fit=crop&w=600&q=80"],
    tags: ["usb-c hub", "type c", "adapter", "hdmi", "laptop"]
  },

  // ==========================================
  // 4. HOSTEL ESSENTIALS
  // ==========================================
  {
    id: "hos-001",
    name: "4-Socket Spike Guard Extension Board (3m Heavy Cord)",
    category: "hostel",
    categoryLabel: "Hostel Essentials",
    price: 399,
    cost: 240,
    originalPrice: 549,
    rating: 4.9,
    reviewsCount: 220,
    badge: "Hostel Must-Have",
    description: "Fire-retardant surge protector with 4 universal sockets, individual switches with LED indicators, and 3-meter heavy copper cord.",
    specs: ["4 Universal Sockets with safety shutters", "Individual On/Off switches", "3-Meter fire-resistant cable", "Built-in Surge & Spike protection"],
    inStock: true,
    stockCount: 60,
    image: "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=600&q=80"],
    tags: ["extension board", "spike guard", "hostel", "power"]
  },
  {
    id: "hos-002",
    name: "Multi-Cook Stainless Steel Electric Kettle (1.5L)",
    category: "hostel",
    categoryLabel: "Hostel Essentials",
    price: 649,
    cost: 390,
    originalPrice: 899,
    rating: 4.8,
    reviewsCount: 165,
    badge: "Late Night Savior",
    description: "1500W rapid-boil food grade 304 stainless steel electric kettle with auto shut-off and boil-dry safety protection for tea, coffee, and noodles.",
    specs: ["1.5 Litre Capacity", "1500W Fast Boil Heating Element", "Auto shut-off on boiling", "360-degree swivel base"],
    inStock: true,
    stockCount: 28,
    image: "https://images.unsplash.com/photo-1594213114663-ddf4f240f08d?auto=format&fit=crop&w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1594213114663-ddf4f240f08d?auto=format&fit=crop&w=600&q=80"],
    tags: ["electric kettle", "kettle", "hostel", "boil", "maggi"]
  },
  {
    id: "hos-003",
    name: "Rechargeable LED Study Desk Lamp (3 Color Modes)",
    category: "hostel",
    categoryLabel: "Hostel Essentials",
    price: 499,
    cost: 300,
    originalPrice: 699,
    rating: 4.7,
    reviewsCount: 140,
    badge: "Eye-Care Tech",
    description: "Flexible gooseneck study lamp with touch dimmer, 3 lighting modes (Warm, Natural, White), and 2000mAh backup battery for power cuts.",
    specs: ["3 Color temperatures (3000K-6000K)", "Touch control with stepless dimming", "2000mAh USB Rechargeable battery", "360° Flexible silicone neck"],
    inStock: true,
    stockCount: 35,
    image: "https://images.unsplash.com/photo-1534353436294-0dbd4bdac845?auto=format&fit=crop&w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1534353436294-0dbd4bdac845?auto=format&fit=crop&w=600&q=80"],
    tags: ["study lamp", "desk lamp", "led lamp", "hostel"]
  },
  {
    id: "hos-004",
    name: "Foldable Mesh Laundry Hamper Basket",
    category: "hostel",
    categoryLabel: "Hostel Essentials",
    price: 249,
    cost: 150,
    originalPrice: 349,
    rating: 4.6,
    reviewsCount: 85,
    badge: "Space Saver",
    description: "Pop-up breathable mesh laundry bag with sturdy side handles and side pocket for detergent packets and wash tokens.",
    specs: ["Pop-up collapsible design", "High-density breathable mesh", "Sturdy reinforced carry handles", "Holds up to 10kg clothes"],
    inStock: true,
    stockCount: 40,
    image: "https://images.unsplash.com/photo-1582735689369-4fe89db7114c?auto=format&fit=crop&w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1582735689369-4fe89db7114c?auto=format&fit=crop&w=600&q=80"],
    tags: ["laundry basket", "hamper", "hostel", "clothes"]
  },
  {
    id: "hos-005",
    name: "100% Cotton Single Bedsheet with Pillow Cover",
    category: "hostel",
    categoryLabel: "Hostel Essentials",
    price: 399,
    cost: 240,
    originalPrice: 599,
    rating: 4.7,
    reviewsCount: 104,
    badge: "Hostel Bedding",
    description: "Super soft breathable 200 TC cotton single bedsheet sized perfectly for standard hostel single beds.",
    specs: ["Size: 60 x 90 inches (Single Bed)", "Includes 1 matching pillow cover", "200 Thread Count Breathable Cotton", "Machine washable & fade resistant"],
    inStock: true,
    stockCount: 50,
    image: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=600&q=80"],
    tags: ["bedsheet", "bedding", "pillow cover", "hostel"]
  },
  {
    id: "hos-006",
    name: "Heavy-Duty Plastic Bucket & Mug Combo Set",
    category: "hostel",
    categoryLabel: "Hostel Essentials",
    price: 299,
    cost: 180,
    originalPrice: 420,
    rating: 4.8,
    reviewsCount: 92,
    badge: "Essential",
    description: "Durable 18-liter virgin plastic bathroom bucket with sturdy steel handle and matching 1-liter measuring mug.",
    specs: ["18L Virgin Plastic Bucket", "1L Matching bath mug", "Rust-proof chrome handle", "Crack & stress resistant"],
    inStock: true,
    stockCount: 45,
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80",
    gallery: ["https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80"],
    tags: ["bucket", "mug", "bathroom", "hostel"]
  }
];

const PAYMENT_INFO = {
  bank: {
    bankName: "State Bank of India (SBI)",
    accountNumber: "43626003401",
    accountType: "Saving",
    ifscCode: "SBIN0051455",
    accountHolder: "Harpreet Singh / Campus Store"
  },
  upi: {
    gpay: "singhharpreet5975@okaxis",
    phonepe: "7009918303@ybl"
  },
  fulfillmentContacts: {
    emails: ["singhharpreet5975@gmail.com"],
    supportEmail: "singhharpreet5975@gmail.com",
    whatsappNumbers: [
      { number: "917009918303", label: "+91 70099 18303 (Inventory Manager)" }
    ]
  }
};
